# permissions for end users to view promotiontemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: promotiontemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: release-promotion-operator
    app.kubernetes.io/part-of: release-promotion-operator
    app.kubernetes.io/managed-by: kustomize
  name: promotiontemplate-viewer-role
rules:
- apiGroups:
  - api.release-promotion-operator.io
  resources:
  - promotiontemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.release-promotion-operator.io
  resources:
  - promotiontemplates/status
  verbs:
  - get
