apiVersion: api.release-promotion-operator.io/v1alpha1
kind: Environment
metadata:
  labels:
    app.kubernetes.io/name: environment
    app.kubernetes.io/instance: environment-sample
    app.kubernetes.io/part-of: release-promotion-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: release-promotion-operator
  name: environment-sample
spec:
  # TODO(user): Add fields here
