apiVersion: api.release-promotion-operator.io/v1alpha1
kind: Promotion
metadata:
  name: dev-to-prod
spec:
  from:
    environmentRef:
      name: dev
  to:
    environmentRef:
      name: prod
  templateRef:
    name: promotiontemplate-sample
  strategy:
    pull-request: true
  readinessChecks:
    localObjectsRef:
      - name: deployment-sample-1
        groupVersionResource:
          group: apps
          version: v1
          resource: deployments
