apiVersion: api.release-promotion-operator.io/v1alpha1
kind: Promotion
metadata:
  labels:
    app.kubernetes.io/name: promotion
    app.kubernetes.io/instance: promotion-sample
    app.kubernetes.io/part-of: release-promotion-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: release-promotion-operator
  name: promotion-sample
spec:
  # TODO(user): Add fields here
