apiVersion: api.release-promotion-operator.io/v1alpha1
kind: Promotion
metadata:
  name: dev-to-prod
spec:
  from:
    environmentRef:
      name: dev
  to:
    environmentRef:
      name: prod
  strategy:
    pull-request: true
