apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-sample-1
  name: deployment-sample-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-sample-1
  template:
    metadata:
      labels:
        app: deployment-sample-1
    spec:
      containers:
      - image: nginx
        name: nginx
